/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 05:49:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ogudoctor.cal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class age_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".ccSDWw {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-pack: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    height: 35px;\n");
      out.write("    border-bottom: 1px solid rgb(228, 228, 230);\n");
      out.write("    background-color: white;\n");
      out.write("}\n");
      out.write(".gWFIhC {\n");
      out.write("    position: relative;\n");
      out.write("    z-index: 1;\n");
      out.write("    height: 30px;\n");
      out.write("    padding: 0px 25px;\n");
      out.write("    font-size: 13px;\n");
      out.write("    line-height: 16px;\n");
      out.write("    font-weight: 500;\n");
      out.write("    text-decoration: none;\n");
      out.write("    color: rgb(134, 134, 136);\n");
      out.write("}\n");
      out.write("/* a:-webkit-any-link {\n");
      out.write("    color: -webkit-link;\n");
      out.write("    cursor: pointer;\n");
      out.write("    text-decoration: underline;\n");
      out.write("} */\n");
      out.write(".huFlcW {\n");
      out.write("    position: relative;\n");
      out.write("    z-index: 1;\n");
      out.write("    height: 30px;\n");
      out.write("    padding: 0px 25px;\n");
      out.write("    font-size: 13px;\n");
      out.write("    line-height: 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    background-color: rgb(255, 255, 255);\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("/* user agent stylesheet\n");
      out.write("a:-webkit-any-link {\n");
      out.write("    color: -webkit-link;\n");
      out.write("    cursor: pointer;\n");
      out.write("    text-decoration: underline;\n");
      out.write("} */\n");
      out.write(".dDWxH {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-pack: end;\n");
      out.write("    justify-content: flex-end;\n");
      out.write("    margin: 0px auto;\n");
      out.write("    max-width: 620px;\n");
      out.write("    position: relative;\n");
      out.write("    height: 400px;\n");
      out.write("    z-index:-1;\n");
      out.write("}\n");
      out.write(".gmQRFo {\n");
      out.write("    padding-top: 93px;\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    position: absolute;\n");
      out.write("    top: 0px;\n");
      out.write("    left: 0px;\n");
      out.write("    z-index: 1;\n");
      out.write("}\n");
      out.write(".cFMBsW {\n");
      out.write("    margin: 0px;\n");
      out.write("    white-space: nowrap;\n");
      out.write("}\n");
      out.write("h1 {\n");
      out.write("    display: block;\n");
      out.write("    font-size: 2em;\n");
      out.write("    margin-block-start: 0.67em;\n");
      out.write("    margin-block-end: 0.67em;\n");
      out.write("    margin-inline-start: 0px;\n");
      out.write("    margin-inline-end: 0px;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write(".eTgrRq {\n");
      out.write("    color: rgb(242, 152, 51);\n");
      out.write("    font-size: inherit;\n");
      out.write("    line-height: inherit;\n");
      out.write("    white-space: nowrap;\n");
      out.write("}\n");
      out.write(".iCJkkn {\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    font-size: 38px;\n");
      out.write("    line-height: 1.315em;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    margin: 0px;\n");
      out.write("}\n");
      out.write(".iRdXUj {\n");
      out.write("    font-size: 16px;\n");
      out.write("    margin: 0px;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    color: rgb(134, 134, 136);\n");
      out.write("}\n");
      out.write(".bFEDlq {\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    font-size: 16px;\n");
      out.write("    line-height: 1.75em;\n");
      out.write("    font-family: \"Apple SD Gothic Neo\";\n");
      out.write("}\n");
      out.write(".dZVjNB {\n");
      out.write("    width: 400px;\n");
      out.write("    height: 400px;\n");
      out.write("}\n");
      out.write("img {\n");
      out.write("    overflow-clip-margin: content-box;\n");
      out.write("    overflow: clip;\n");
      out.write("}\n");
      out.write(".jyMFKB {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-pack: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    padding: 80px 0px;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("}\n");
      out.write(".hofxzw {\n");
      out.write("    padding: 60px 50px;\n");
      out.write("    width: 620px;\n");
      out.write("    background-color: rgb(255, 255, 255);\n");
      out.write("    border-radius: 14px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    box-shadow: rgba(222, 222, 224, 0.65) 0px 12px 25px -20px;\n");
      out.write("}\n");
      out.write("form {\n");
      out.write("    display: block;\n");
      out.write("    margin-top: 0em;\n");
      out.write("}\n");
      out.write(".jjmNcZ {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    align-items: flex-end;\n");
      out.write("    margin-bottom: 32px;\n");
      out.write("}\n");
      out.write(".sXbo {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("    width: 100%;\n");
      out.write("}\n");
      out.write(".bnlRbj {\n");
      out.write("    width: 160px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    padding: 10px 0px;\n");
      out.write("    white-space: pre-line;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    font-size: 16px;\n");
      out.write("    line-height: 1.75;\n");
      out.write("    letter-spacing: -0.32px;\n");
      out.write("}\n");
      out.write("label {\n");
      out.write("    cursor: default;\n");
      out.write("}\n");
      out.write(".jGNyzc {\n");
      out.write("    display: flex;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    max-width: 360px;\n");
      out.write("}\n");
      out.write(".liyBtK {\n");
      out.write("    border-radius: 10px;\n");
      out.write("    border: 5px solid rgb(252, 209, 30);\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-pack: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    flex-direction: column;\n");
      out.write("    width: 170px;\n");
      out.write("    height: 150px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    margin-right: 20px;\n");
      out.write("    background-color: rgb(255, 255, 255);\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("}\n");
      out.write(".liyBtK img {\n");
      out.write("    opacity: 1;\n");
      out.write("}\n");
      out.write(".lbTxgq {\n");
      out.write("    width: 110px;\n");
      out.write("    height: 110px;\n");
      out.write("    background: transparent;\n");
      out.write("    opacity: 0.35;\n");
      out.write("    mix-blend-mode: multiply;\n");
      out.write("}\n");
      out.write(".gqcnzR {\n");
      out.write("    text-align: center;\n");
      out.write("    font-weight: bold;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    margin: 0px;\n");
      out.write("    color: inherit;\n");
      out.write("}\n");
      out.write(".iempoK:last-child {\n");
      out.write("    margin-right: 0px;\n");
      out.write("}\n");
      out.write(".iempoK {\n");
      out.write("    border-radius: 10px;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("    border: 5px solid rgb(246, 247, 248);\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-pack: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    flex-direction: column;\n");
      out.write("    width: 170px;\n");
      out.write("    height: 150px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    color: rgb(207, 206, 206);\n");
      out.write("    margin-right: 20px;\n");
      out.write("}\n");
      out.write(".jpeBZh {\n");
      out.write("    width: 100%;\n");
      out.write("    max-width: 360px;\n");
      out.write("    text-align: right;\n");
      out.write("    height: 48px;\n");
      out.write("    border-radius: 14px;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    border: 2px solid transparent;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write(".gpdHNn {\n");
      out.write("    padding-right: 10px;\n");
      out.write("    padding-left: 21px;\n");
      out.write("    width: 24px;\n");
      out.write("    height: 24px;\n");
      out.write("}\n");
      out.write("element.style {\n");
      out.write("    width: 24px;\n");
      out.write("    height: 24px;\n");
      out.write("}\n");
      out.write("svg:not(:root) {\n");
      out.write("    overflow-clip-margin: content-box;\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write("path[Attributes Style] {\n");
      out.write("    d: path(\"M 0 0 H 1260 V 1948 H 0 Z\");\n");
      out.write("    transform: translate(-100, -1824);\n");
      out.write("}\n");
      out.write(":not(svg) {\n");
      out.write("    transform-origin: 0px 0px;\n");
      out.write("}\n");
      out.write("path[Attributes Style] {\n");
      out.write("    fill: rgb(207, 206, 206);\n");
      out.write("    d: path(\"M 117.657 1827 c 0.39 0 0.713 0.29 0.765 0.667 l 0.007 0.104 v 1.298 c 1.441 0.13 2.571 1.341 2.571 2.817 v 10.285 c 0 1.563 -1.266 2.829 -2.829 2.829 H 105.83 c -1.563 0 -2.829 -1.266 -2.829 -2.829 v -10.285 c 0 -1.476 1.13 -2.687 2.571 -2.817 v -1.298 c 0 -0.426 0.346 -0.771 0.772 -0.771 c 0.39 0 0.713 0.29 0.764 0.667 l 0.007 0.104 v 1.286 h 4.114 v -1.286 c 0 -0.39 0.29 -0.713 0.667 -0.764 L 112 1827 c 0.39 0 0.713 0.29 0.764 0.667 l 0.007 0.104 v 1.286 h 4.114 v -1.286 c 0 -0.39 0.29 -0.713 0.667 -0.764 l 0.105 -0.007 Z m 1.8 8.228 h -14.915 v 6.943 c 0 0.71 0.576 1.286 1.287 1.286 h 12.342 c 0.71 0 1.286 -0.575 1.286 -1.286 v -6.943 Z m -1.286 -4.628 H 105.83 c -0.71 0 -1.286 0.576 -1.286 1.286 l -0.001 1.799 h 14.915 v -1.8 c 0 -0.71 -0.575 -1.285 -1.286 -1.285 Z\");\n");
      out.write("    transform: translate(-100, -1824);\n");
      out.write("}\n");
      out.write(".dIZwNu {\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    height: 26px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    outline: none;\n");
      out.write("    border: none;\n");
      out.write("    width: 100%;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("input:not([type=\"range\"]):not([type=\"color\"]) {\n");
      out.write("    writing-mode: horizontal-tb !important;\n");
      out.write("}\n");
      out.write("input:not([type=\"file\" i], [type=\"image\" i], [type=\"checkbox\" i], [type=\"radio\" i]) {\n");
      out.write("}\\\n");
      out.write(".iunTGn > div {\n");
      out.write("    margin-right: 16px;\n");
      out.write("}\n");
      out.write(".iunTGn {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("}\n");
      out.write(".ioNcga {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("}\n");
      out.write(".jXKbJV {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    color: rgb(207, 206, 206);\n");
      out.write("    min-width: 70px;\n");
      out.write("    padding: 0px;\n");
      out.write("    margin: 0px;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    font-size: 14px;\n");
      out.write("    line-height: 1.86;\n");
      out.write("}\n");
      out.write("eYsNwq {\n");
      out.write("    padding: 3px 0px;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("    margin: 0px 10px 0px 0px;\n");
      out.write("    appearance: none;\n");
      out.write("    width: 20px;\n");
      out.write("    height: 20px;\n");
      out.write("    border-radius: 14px;\n");
      out.write("    outline: none;\n");
      out.write("}\n");
      out.write("input:not([type=\"range\"]):not([type=\"color\"]) {\n");
      out.write("    writing-mode: horizontal-tb !important;\n");
      out.write("}\n");
      out.write(".ecnULt {\n");
      out.write("    display: flex;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    min-width: 70px;\n");
      out.write("    padding: 0px;\n");
      out.write("    margin: 0px;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    font-size: 14px;\n");
      out.write("    line-height: 1.86;\n");
      out.write("}\n");
      out.write(".eYsNwq:checked {\n");
      out.write("    border: 5px solid rgb(252, 209, 30);\n");
      out.write("    background-color: rgb(255, 255, 255);\n");
      out.write("}\n");
      out.write(".jrTReh {\n");
      out.write("    margin: 60px 70px 0px;\n");
      out.write("}\n");
      out.write(".xWwDG {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 48px;\n");
      out.write("    border-radius: 14px;\n");
      out.write("    border: none;\n");
      out.write("    outline: none;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    background-color: rgb(252, 209, 30);\n");
      out.write("}\n");
      out.write("sc-fbJfA {\n");
      out.write("	z-index: -1;\n");
      out.write("}\n");
      out.write(".liyBtK:last-child {\n");
      out.write("    margin-right: 0px;\n");
      out.write("}\n");
      out.write(".oLOis {\n");
      out.write("	width: 100%;\n");
      out.write("	max-width: 360px;\n");
      out.write("	text-align: right;\n");
      out.write("	height: 48px;\n");
      out.write("	border-radius: 14px;\n");
      out.write("	background-color: rgb(246, 247, 248);\n");
      out.write("	display: flex;\n");
      out.write("	-webkit-box-align: center;\n");
      out.write("	align-items: center;\n");
      out.write("	border: 2px solid rgb(252, 209, 30);\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".eYsNwq {\n");
      out.write("    padding: 3px 0px;\n");
      out.write("    background-color: rgb(246, 247, 248);\n");
      out.write("    margin: 0px 10px 0px 0px;\n");
      out.write("    appearance: none;\n");
      out.write("    width: 20px;\n");
      out.write("    height: 20px;\n");
      out.write("    border-radius: 14px;\n");
      out.write("    outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("		<header>\n");
      out.write("        	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_top.jsp", out, false);
      out.write("\n");
      out.write("    	</header>\n");
      out.write("	<main class=\"sc-bCDidY kZZDuN ageJsp\">\n");
      out.write("		<div>\n");
      out.write("			<div class=\"sc-jMAIzZ fNDbMx\">\n");
      out.write("				<ul class=\"sc-dQelHR kYqwoU\">\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			<div class=\"sc-ehsgIH ccSDWw\">\n");
      out.write("				<div>\n");
      out.write("					<a class=\"sc-fbJfA gWFIhC\" href=\"/food.do\">사료칼로리</a><a\n");
      out.write("						class=\"sc-fbJfA gWFIhC\" href=\"/recommend.do\">권장칼로리</a><a\n");
      out.write("						class=\"sc-fbJfA gWFIhC\" href=\"/bmi.do\">비만도</a><a\n");
      out.write("						class=\"sc-fbJfA huFlcW\" href=\"/age.do\">나이</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"sc-ldFCYb dDWxH\">\n");
      out.write("			<div class=\"sc-gHyekI gmQRFo\">\n");
      out.write("				<h1 class=\"sc-cPlDXj sc-cmEail iCJkkn cFMBsW\">\n");
      out.write("					<span color=\"#f29833\" class=\"sc-hjsqBZ eTgrRq\">나이계산기</span>란?\n");
      out.write("				</h1>\n");
      out.write("				<p class=\"sc-kZGvTt sc-eZYOHW bFEDlq iRdXUj\">\n");
      out.write("					우리 아이의 나이,<br>사람나이로는 몇살일까요?\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			<img src=\"/resources/images/ageMain.png\"\n");
      out.write("				class=\"sc-FeKFz dZVjNB\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"sc-jOQpHc jyMFKB\">\n");
      out.write("			<form class=\"sc-ftWlEF hofxzw\">\n");
      out.write("				<div class=\"sc-dskThN jjmNcZ\">\n");
      out.write("					<div class=\"sc-cYRmzm sXbo\">\n");
      out.write("						<label class=\"sc-hNeXkk bnlRbj\">반려동물 종류</label>\n");
      out.write("						<div class=\"sc-fGjrnr jGNyzc\">\n");
      out.write("							<div class=\"sc-dsInJy iempoK selPet\">\n");
      out.write("								<img src=\"/resources/images/dog.png\" \n");
      out.write("									alt=\"Option Image\" class=\"sc-dlUsjx lbTxgq\">\n");
      out.write("								<p class=\"sc-YtoFE gqcnzR\">강아지</p>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"sc-dsInJy iempoK selPet\">\n");
      out.write("								<img src=\"/resources/images/cat.png\" \n");
      out.write("									alt=\"Option Image\" class=\"sc-dlUsjx lbTxgq\">\n");
      out.write("								<p class=\"sc-YtoFE gqcnzR\">고양이</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sc-dskThN jjmNcZ\">\n");
      out.write("					<div class=\"sc-cYRmzm sXbo\">\n");
      out.write("						<label class=\"sc-hNeXkk bnlRbj\">생년월일</label>\n");
      out.write("						<div class=\"sc-gtIISA jpeBZh\">\n");
      out.write("							<div class=\"sc-bYOEQd gpdHNn\">\n");
      out.write("								<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"\n");
      out.write("									style=\"width: 24px; height: 24px;\">\n");
      out.write("									<g fill=\"none\">\n");
      out.write("									<path fill=\"transition\" d=\"M0 0H1260V1948H0z\"\n");
      out.write("										transform=\"translate(-100 -1824)\"></path>\n");
      out.write("									<path fill=\"#cfcece\"\n");
      out.write("										d=\"M117.657 1827c.39 0 .713.29.765.667l.007.104v1.298c1.441.13 2.571 1.341 2.571 2.817v10.285c0 1.563-1.266 2.829-2.829 2.829H105.83c-1.563 0-2.829-1.266-2.829-2.829v-10.285c0-1.476 1.13-2.687 2.571-2.817v-1.298c0-.426.346-.771.772-.771.39 0 .713.29.764.667l.007.104v1.286h4.114v-1.286c0-.39.29-.713.667-.764L112 1827c.39 0 .713.29.764.667l.007.104v1.286h4.114v-1.286c0-.39.29-.713.667-.764l.105-.007zm1.8 8.228h-14.915v6.943c0 .71.576 1.286 1.287 1.286h12.342c.71 0 1.286-.575 1.286-1.286v-6.943zm-1.286-4.628H105.83c-.71 0-1.286.576-1.286 1.286l-.001 1.799h14.915v-1.8c0-.71-.575-1.285-1.286-1.285z\"\n");
      out.write("										transform=\"translate(-100 -1824)\"></path></g></svg>\n");
      out.write("							</div>\n");
      out.write("							<input placeholder=\"0000 . 00\" class=\"sc-FIATH dIZwNu\"\n");
      out.write("								value=\"\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sc-dskThN jjmNcZ perSize\" style=\"display:none;\">\n");
      out.write("					<div class=\"sc-cYRmzm sXbo\">\n");
      out.write("						<label class=\"sc-hNeXkk bnlRbj\">반려동물 크기</label>\n");
      out.write("						<div class=\"sc-gHbYXZ iunTGn\">\n");
      out.write("							<div class=\"sc-crPCXo ioNcga\">\n");
      out.write("								<label color=\"#cfcece\" class=\"sc-dExYQz jXKbJV\"><input\n");
      out.write("									type=\"radio\" class=\"sc-bqWVmG eYsNwq\" value=\"소형\">소형</label>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"sc-crPCXo ioNcga\">\n");
      out.write("								<label color=\"#cfcece\" class=\"sc-dExYQz jXKbJV\"><input\n");
      out.write("									type=\"radio\" class=\"sc-bqWVmG eYsNwq\" value=\"중형\">중형</label>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"sc-crPCXo ioNcga\">\n");
      out.write("								<label color=\"#cfcece\" class=\"sc-dExYQz jXKbJV\"><input\n");
      out.write("									type=\"radio\" class=\"sc-bqWVmG eYsNwq\" value=\"대형\">대형</label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sc-faCEWe jrTReh\">\n");
      out.write("					<button type=\"button\" class=\"sc-fYdXmn xWwDG getResult\">결과보기</button>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function(){\n");
      out.write("	init();\n");
      out.write("});\n");
      out.write("\n");
      out.write("function init(){\n");
      out.write("	var $jsp = $('.ageJsp');\n");
      out.write("	\n");
      out.write("	$jsp.find('.selPet').on('click',function() {\n");
      out.write("		$jsp.find('.sc-dsInJy').removeClass('liyBtK').addClass('iempoK');\n");
      out.write("		if ($(this).find('.sc-YtoFE').text() == '고양이' && $(this).hasClass('liyBtK')) {\n");
      out.write("			$(this).removeClass('liyBtK').addClass('iempoK');\n");
      out.write("		} else if ($(this).find('.sc-YtoFE').text() == '고양이' && $(this).hasClass('iempoK')) {\n");
      out.write("			$jsp.find('.perSize').hide();\n");
      out.write("			$(this).removeClass('iempoK').addClass('liyBtK');\n");
      out.write("		}\n");
      out.write("		if ($(this).find('.sc-YtoFE').text() == '강아지' && $(this).hasClass('liyBtK')) {\n");
      out.write("			$(this).removeClass('liyBtK').addClass('iempoK');\n");
      out.write("		} else if ($(this).find('.sc-YtoFE').text() == '강아지' && $(this).hasClass('iempoK')) {\n");
      out.write("			$jsp.find('.perSize').show();\n");
      out.write("			$(this).removeClass('iempoK').addClass('liyBtK');\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$jsp.find('.sc-FIATH').on('focus',function() {\n");
      out.write("	    $(this).closest('.sc-gtIISA').removeClass('jpeBZh').addClass('oLOis');\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	$jsp.find('.sc-FIATH').on('blur',function() {\n");
      out.write("		$(this).closest('.sc-gtIISA').removeClass('oLOis').addClass('jpeBZh');\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$jsp.find('input[type=\"radio\"]').on('click', function() {\n");
      out.write("	    if ($(this).is(':checked')) {\n");
      out.write("	        var $radioGroup = $(this).closest('.sc-gHbYXZ').find('.sc-dExYQz');\n");
      out.write("	        $radioGroup.find('input[type=\"radio\"]').prop('checked', false);\n");
      out.write("	        $radioGroup.removeClass('ecnULt').addClass('jXKbJV');\n");
      out.write("	        \n");
      out.write("	        var $currentInput = $(this).closest('.sc-dExYQz');\n");
      out.write("	        $currentInput.removeClass('jXKbJV').addClass('ecnULt');\n");
      out.write("	        $(this).prop('checked', true);\n");
      out.write("	    }\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$jsp.find('.sc-FIATH').on('keyup', function(event) {\n");
      out.write("		\n");
      out.write("	    this.value = this.value.replace(/[^0-9\\.]/g, '');\n");
      out.write("		\n");
      out.write("	    if(event.key != \"Backspace\" && this.value.length == 4) {\n");
      out.write("	        this.value += '.';\n");
      out.write("	    }\n");
      out.write("	    \n");
      out.write("	    if (this.value.length > 7) {\n");
      out.write("	        this.value = this.value.substr(0, 7);\n");
      out.write("	    }\n");
      out.write("\n");
      out.write("	    if (/^\\d{4}\\.\\d{2}$/.test(this.value)) {\n");
      out.write("	        this.removeEventListener('input', arguments.callee);\n");
      out.write("	    }\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	// 결과보기 버튼 이벤트\n");
      out.write("	$jsp.find('.getResult').on('click',function(){\n");
      out.write("		location.replace('/age_result.do')\n");
      out.write("	});\n");
      out.write("};\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
