/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 05:47:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ogudoctor.cal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ogu_005fcal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".erwwoY {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-pack: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	padding: 80px 0px 110px;\r\n");
      out.write("}\r\n");
      out.write("@media only screen and (max-width: 961px) .kHOuNn {\r\n");
      out.write("	max-width : 500px;\r\n");
      out.write("	flex-wrap : wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kHOuNn {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	-webkit-box-pack: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hbDeHl {\r\n");
      out.write("	padding: 32px 30px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	background-color: rgb(254, 250, 238);\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	box-shadow: rgba(222, 222, 224, 0.65) 0px 30px 20px -10px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jZEtsG {\r\n");
      out.write("	padding: 32px 30px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	background-color: rgb(247, 244, 255);\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	box-shadow: rgba(222, 222, 224, 0.65) 0px 30px 20px -10px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".eCpdOD {\r\n");
      out.write("	padding: 32px 30px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	background-color: rgb(236, 246, 255);\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	box-shadow: rgba(222, 222, 224, 0.65) 0px 30px 20px -10px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gEnSjk {\r\n");
      out.write("	padding: 32px 30px;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	background-color: rgb(255, 243, 229);\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	box-shadow: rgba(222, 222, 224, 0.65) 0px 30px 20px -10px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fTvbXT {\r\n");
      out.write("	color: rgb(9, 9, 9);\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	line-height: 1.35em;\r\n");
      out.write("	font-family: JalnanOTF;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hgkyti {\r\n");
      out.write("	color: rgb(88, 67, 190);\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	line-height: inherit;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edaEBF {\r\n");
      out.write("	color: rgb(78, 127, 28);\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	line-height: inherit;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ejZDiW {\r\n");
      out.write("	color: rgb(59, 116, 200);\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	line-height: inherit;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".eTgrRq {\r\n");
      out.write("	color: rgb(242, 152, 51);\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	line-height: inherit;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gpAQee {\r\n");
      out.write("	width: 48px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	background-color: rgb(78, 127, 28);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 30px;\r\n");
      out.write("	bottom: 30px;\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".TBWyR {\r\n");
      out.write("	width: 48px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	background-color: rgb(88, 67, 190);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 30px;\r\n");
      out.write("	bottom: 30px;\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jqPQZt {\r\n");
      out.write("	width: 48px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	background-color: rgb(59, 116, 200);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 30px;\r\n");
      out.write("	bottom: 30px;\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cOjuuJ {\r\n");
      out.write("	width: 48px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	background-color: rgb(242, 152, 51);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 30px;\r\n");
      out.write("	bottom: 30px;\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write(".dDWxH {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    -webkit-box-pack: end;\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    margin: 0px auto;\r\n");
      out.write("    max-width: 620px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 400px;\r\n");
      out.write("}\r\n");
      out.write(".gmQRFo {\r\n");
      out.write("    padding-top: 93px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0px;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write(".cFMBsW {\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write(".iCJkkn {\r\n");
      out.write("    color: rgb(9, 9, 9);\r\n");
      out.write("    font-size: 38px;\r\n");
      out.write("    line-height: 1.315em;\r\n");
      out.write("    font-family: JalnanOTF;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 2em;\r\n");
      out.write("    margin-block-start: 0.67em;\r\n");
      out.write("    margin-block-end: 0.67em;\r\n");
      out.write("    margin-inline-start: 0px;\r\n");
      out.write("    margin-inline-end: 0px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".iRdXUj {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    color: rgb(134, 134, 136);\r\n");
      out.write("}\r\n");
      out.write(".bFEDlq {\r\n");
      out.write("    color: rgb(9, 9, 9);\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    line-height: 1.75em;\r\n");
      out.write("    font-family: \"Apple SD Gothic Neo\";\r\n");
      out.write("}\r\n");
      out.write("img {\r\n");
      out.write("    overflow-clip-margin: content-box;\r\n");
      out.write("    overflow: clip;\r\n");
      out.write("}\r\n");
      out.write("footer{\r\n");
      out.write("	width:1920px;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	margin-top:20px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_top.jsp", out, false);
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"sc-ldFCYb dDWxH\" style=\"position: relative; z-index: -1;\">\r\n");
      out.write("		<div class=\"sc-gHyekI gmQRFo\">\r\n");
      out.write("			<h1 class=\"sc-cPlDXj sc-cmEail iCJkkn cFMBsW\">건강 계산기</h1>\r\n");
      out.write("			<p class=\"sc-kZGvTt sc-eZYOHW bFEDlq iRdXUj\">우리 아이 건강을 위한 계산기 모음</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<img src=\"/resources/images/samoMain.png\"\r\n");
      out.write("			class=\"sc-FeKFz dZVjNB\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"sc-bbpGSz erwwoY\">\r\n");
      out.write("		<div class=\"sc-jPYHJC kHOuNn\">\r\n");
      out.write("			<div class=\"sc-dxroEu hbDeHl\">\r\n");
      out.write("				<h2 class=\"sc-BKAtq fTvbXT\">\r\n");
      out.write("					<span color=\"#4e7f1c\" class=\"sc-hjsqBZ edaEBF\">사료칼로리</span><br>계산기\r\n");
      out.write("				</h2>\r\n");
      out.write("				<!-- <a href=\"/food.do\">사료칼로 페이지이동</a> -->\r\n");
      out.write("				<a href=\"/food.do\"><button color=\"#4e7f1c\"\r\n");
      out.write("						class=\"sc-fYdXmn sc-UxxwN dGATho gpAQee\">&gt;</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sc-dxroEu jZEtsG\">\r\n");
      out.write("				<h2 class=\"sc-BKAtq fTvbXT\">\r\n");
      out.write("					<span color=\"#5843be\" class=\"sc-hjsqBZ hgkyti\">권장칼로리</span><br>계산기\r\n");
      out.write("				</h2>\r\n");
      out.write("				<a href=\"/recommend.do\"><button color=\"#5843be\"\r\n");
      out.write("						class=\"sc-fYdXmn sc-UxxwN dGATho TBWyR\">&gt;</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sc-dxroEu eCpdOD\">\r\n");
      out.write("				<h2 class=\"sc-BKAtq fTvbXT\">\r\n");
      out.write("					<span color=\"#3b74c8\" class=\"sc-hjsqBZ ejZDiW\">비만도</span><br>계산기\r\n");
      out.write("				</h2>\r\n");
      out.write("				<a href=\"/bmi.do\"><button color=\"#3b74c8\"\r\n");
      out.write("						class=\"sc-fYdXmn sc-UxxwN dGATho jqPQZt\">&gt;</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"sc-dxroEu gEnSjk\">\r\n");
      out.write("				<h2 class=\"sc-BKAtq fTvbXT\">\r\n");
      out.write("					<span color=\"#f29833\" class=\"sc-hjsqBZ eTgrRq\">나이</span><br>계산기\r\n");
      out.write("				</h2>\r\n");
      out.write("				<a href=\"/age.do\"><button color=\"#f29833\"\r\n");
      out.write("						class=\"sc-fYdXmn sc-UxxwN dGATho cOjuuJ\">&gt;</button></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_bottom.jsp", out, false);
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
