/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 05:55:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ogudoctor.cal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommend_002dcalorie_005fresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.eHwBqx {\n");
      out.write("    display: flex;\n");
      out.write("    width: 100%;\n");
      out.write("    flex-direction: column;\n");
      out.write("    -webkit-box-align: center;\n");
      out.write("    align-items: center;\n");
      out.write("    text-align: center;\n");
      out.write("    padding-top: 80px;\n");
      out.write("}\n");
      out.write(".fTvbXT {\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    font-size: 28px;\n");
      out.write("    line-height: 1.35em;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    margin: 0px;\n");
      out.write("}\n");
      out.write("h2 {\n");
      out.write("    display: block;\n");
      out.write("    font-size: 1.5em;\n");
      out.write("    margin-block-start: 0.83em;\n");
      out.write("    margin-block-end: 0.83em;\n");
      out.write("    margin-inline-start: 0px;\n");
      out.write("    margin-inline-end: 0px;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write(".hgkyti {\n");
      out.write("    color: rgb(88, 67, 190);\n");
      out.write("    font-size: inherit;\n");
      out.write("    line-height: inherit;\n");
      out.write("    white-space: nowrap;\n");
      out.write("}\n");
      out.write(".eHAyot {\n");
      out.write("    text-align: center;\n");
      out.write("    margin-top: 40px;\n");
      out.write("    margin-bottom: 80px;\n");
      out.write("    background-color: rgb(247, 244, 255);\n");
      out.write("    border-radius: 14px;\n");
      out.write("    width: 620px;\n");
      out.write("    padding: 50px 40px;\n");
      out.write("    box-shadow: rgba(222, 222, 224, 0.65) 0px 12px 25px -20px;\n");
      out.write("    color: rgb(134, 134, 136);\n");
      out.write("    line-height: 1.75em;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("div {\n");
      out.write("    display: block;\n");
      out.write("}\n");
      out.write(".dpFNWh {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("    text-align: left;\n");
      out.write("    margin-bottom: 30px;\n");
      out.write("    -webkit-box-pack: center;\n");
      out.write("    justify-content: center;\n");
      out.write("}\n");
      out.write(".lesjVg {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write(".hISUjs {\n");
      out.write("    color: rgb(9, 9, 9);\n");
      out.write("    font-size: 16px;\n");
      out.write("    line-height: 1.416em;\n");
      out.write("    font-family: JalnanOTF;\n");
      out.write("    margin: 0px;\n");
      out.write("}\n");
      out.write("h4 {\n");
      out.write("    display: block;\n");
      out.write("    margin-block-start: 1.33em;\n");
      out.write("    margin-block-end: 1.33em;\n");
      out.write("    margin-inline-start: 0px;\n");
      out.write("    margin-inline-end: 0px;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write(".biUFlm {\n");
      out.write("    font-size: 28px;\n");
      out.write("    line-height: 38px;\n");
      out.write("}\n");
      out.write(".hgkyti {\n");
      out.write("    color: rgb(88, 67, 190);\n");
      out.write("    font-size: inherit;\n");
      out.write("    line-height: inherit;\n");
      out.write("    white-space: nowrap;\n");
      out.write("}\n");
      out.write(".lesjVg:last-child {\n");
      out.write("    margin-left: 60px;\n");
      out.write("}\n");
      out.write(".lesjVg {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write("footer{\n");
      out.write("	width:1920px;\n");
      out.write("	display:flex;\n");
      out.write("	margin:auto;\n");
      out.write("	margin-top:20px;\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("		<header>\n");
      out.write("        	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_top.jsp", out, false);
      out.write("\n");
      out.write("    	</header>\n");
      out.write("	<main class=\"sc-bCDidY kZZDuN\">\n");
      out.write("		<div class=\"sc-vjKnw eHwBqx\">\n");
      out.write("			<h2 class=\"sc-BKAtq fTvbXT\">\n");
      out.write("				<span color=\"#5843be\" class=\"sc-hjsqBZ hgkyti\">권장칼로리</span> 결과\n");
      out.write("			</h2>\n");
      out.write("			<div class=\"sc-bjMMwb eHAyot\">\n");
      out.write("				<div class=\"sc-iERabD dpFNWh\">\n");
      out.write("					<div class=\"sc-iqavZe lesjVg\">\n");
      out.write("						<h4 class=\"sc-hVkBjg hISUjs\">1일 권장 칼로리</h4>\n");
      out.write("						<h4 color=\"#090909\" class=\"sc-hVkBjg hISUjs\">\n");
      out.write("							<span color=\"#5843be\" class=\"sc-hjsqBZ sc-eXHjAa hgkyti biUFlm\">409.50</span>\n");
      out.write("							kcal\n");
      out.write("						</h4>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"sc-iqavZe lesjVg\">\n");
      out.write("						<h4 class=\"sc-hVkBjg hISUjs\">1일 기초 대사량</h4>\n");
      out.write("						<h4 color=\"#090909\" class=\"sc-hVkBjg hISUjs\">\n");
      out.write("							<span color=\"#5843be\" class=\"sc-hjsqBZ sc-eXHjAa hgkyti biUFlm\">204.75</span>\n");
      out.write("							kcal\n");
      out.write("						</h4>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<p>\n");
      out.write("					건강 상태, 비만도에 따라 달라질 수 있으니<br>정확한 섭취량은 수의사와 상담해보세요.\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("	<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_bottom.jsp", out, false);
      out.write("\n");
      out.write("	</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
