/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 10:12:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ogudoctor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ogu_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>오구닥터 메인화면</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.maindisplay_banner{\n");
      out.write("		display: flex;\n");
      out.write("		justify-content: center;\n");
      out.write("		margin-top: 20px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	@font-face {\n");
      out.write("	    font-family: 'SBAggroB';\n");
      out.write("	    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/SBAggroB.woff') format('woff');\n");
      out.write("	    font-weight: normal;\n");
      out.write("	    font-style: normal;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_font_group{\n");
      out.write("		width:1920px;\n");
      out.write("		margin:auto;\n");
      out.write("		text-align: center;\n");
      out.write("		font-family: 'SBAggroB';\n");
      out.write("		font-size: 50px;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_font_group a{\n");
      out.write("		text-decoration-line: none;\n");
      out.write("		color: black; \n");
      out.write("	}\n");
      out.write("	.ogudoctor_self{\n");
      out.write("		display: flex;\n");
      out.write("		justify-content: center;\n");
      out.write("		margin-top: 30px;\n");
      out.write("		text-align: center;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_cal{\n");
      out.write("		display: flex;\n");
      out.write("		justify-content: center;\n");
      out.write("		margin-top: 50px;\n");
      out.write("		text-align: center;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_dog_font{\n");
      out.write("		width:50%;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_cat_font{\n");
      out.write("		width:50%;\n");
      out.write("	}\n");
      out.write("	.ogudoctor_cal_font{\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	footer{\n");
      out.write("		width:1920px;\n");
      out.write("		display:flex;\n");
      out.write("		margin:auto;\n");
      out.write("		margin-top:20px;\n");
      out.write("		margin-bottom: 20px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_top.jsp", out, false);
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<div class=\"maindisplay_banner\">\n");
      out.write("	<a href=\"/ogudoctormaindisplay.do\"><img src=\"resources/images/home/mainbanner_ogudoctor.png\"></a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ogudoctor_font_group\">\n");
      out.write("		<div class=\"ogudoctor_self\">\n");
      out.write("			<div class=\"ogudoctor_dog_font\">\n");
      out.write("				<a href=\"/ogu_dog_categorydisplay.do\">강아지 간단 체크 ></a>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ogudoctor_cat_font\">\n");
      out.write("				<a href=\"/ogu_cat_categorydisplay.do\">고양이 간단 체크 ></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"ogudoctor_cal\">\n");
      out.write("			<div class=\"ogudoctor_cal_font\">\n");
      out.write("				<a href=\"/ogudoctorcaldisplay.do\">건강 계산기 ></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_bottom.jsp", out, false);
      out.write("\n");
      out.write("	</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
