/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-24 05:59:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_005fbody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>오구오구 메인화면</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#mainbanner_slide{\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: center;\n");
      out.write("}\n");
      out.write(".w3-left, .w3-right, .w3-badge {\n");
      out.write("	cursor: pointer\n");
      out.write("}\n");
      out.write("\n");
      out.write(".w3-badge {\n");
      out.write("	height: 13px;\n");
      out.write("	width: 13px;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "home_top.jsp", out, false);
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<div class=\"w3-content w3-display-container\">\n");
      out.write("		<div id=\"mainbanner_slide\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_eduexplain.png\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_ogudoctor.png\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_place.png\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_pocket.png\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_lounge.png\">\n");
      out.write("		<img class=\"mySlides\" src=\"resources/images/home/mainbanner_food.png\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle\" style=\"width: 150%\">\n");
      out.write("			<div class=\"w3-left w3-hover-text-khaki\" onclick=\"plusDivs(-1)\">&#10094;</div>\n");
      out.write("			<div class=\"w3-right w3-hover-text-khaki\" onclick=\"plusDivs(1)\">&#10095;</div>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(1)\"></span>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(2)\"></span>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(3)\"></span>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(4)\"></span>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(5)\"></span>\n");
      out.write("				<span class=\"w3-badge demo w3-border w3-transparent w3-hover-white\" onclick=\"currentDiv(6)\"></span>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("	var slideIndex = 0; // 이미지 인덱스 0으로 시작\n");
      out.write("	autoSlide(); // 페이지 로드시 자동 슬라이드 시작\n");
      out.write("\n");
      out.write("	function plusDivs(n) {\n");
      out.write("	    showDivs(slideIndex += n);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function currentDiv(n) {\n");
      out.write("	    showDivs(slideIndex = n);\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function showDivs(n) {\n");
      out.write("	    var i;\n");
      out.write("	    var x = document.getElementsByClassName(\"mySlides\");\n");
      out.write("	    var dots = document.getElementsByClassName(\"demo\");\n");
      out.write("	    if (n > x.length) {slideIndex = 1}\n");
      out.write("	    if (n < 1) {slideIndex = x.length}\n");
      out.write("	    for (i = 0; i < x.length; i++) {\n");
      out.write("	        x[i].style.display = \"none\";  \n");
      out.write("	    }\n");
      out.write("	    for (i = 0; i < dots.length; i++) {\n");
      out.write("	        dots[i].className = dots[i].className.replace(\" w3-white\", \"\");\n");
      out.write("	    }\n");
      out.write("	    x[slideIndex-1].style.display = \"block\";  \n");
      out.write("	    dots[slideIndex-1].className += \" w3-white\";\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function autoSlide() {\n");
      out.write("	    var i;\n");
      out.write("	    var x = document.getElementsByClassName(\"mySlides\");\n");
      out.write("	    var dots = document.getElementsByClassName(\"demo\");\n");
      out.write("	    for (i = 0; i < x.length; i++) {\n");
      out.write("	        x[i].style.display = \"none\";  \n");
      out.write("	    }\n");
      out.write("	    slideIndex++;\n");
      out.write("	    if (slideIndex > x.length) {slideIndex = 1}\n");
      out.write("	    for (i = 0; i < dots.length; i++) {\n");
      out.write("	        dots[i].className = dots[i].className.replace(\" w3-white\", \"\");\n");
      out.write("	    }\n");
      out.write("	    x[slideIndex-1].style.display = \"block\";  \n");
      out.write("	    dots[slideIndex-1].className += \" w3-white\";\n");
      out.write("	    setTimeout(autoSlide, 3000); // 3초마다 자동 슬라이드 실행\n");
      out.write("	}\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
