/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-22 10:50:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ogudoctor.self;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ogu_005fdog_005fcategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오구닥터 간단체크-강아지</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f5f7ff;\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("}\r\n");
      out.write("section {\r\n");
      out.write("	width: 100vmin;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	transform: translate(-50%, -50%);\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("}\r\n");
      out.write(".tile {\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	width: 170px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("	height: 80%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"] {\r\n");
      out.write("	-webkit-appearance: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border: 3px solid transparent;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	box-shadow: 15px 15px 25px rgba(2, 28, 53, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"checkbox\"]:after {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	font-family: \"Font Awesome 5 Free\";\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	content: \"\\f111\";\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	top: 10px;\r\n");
      out.write("	left: 10px;\r\n");
      out.write("	color: #e2e6f3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"checkbox\"]:hover {\r\n");
      out.write("	transform: scale(1.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"checkbox\"]:checked {\r\n");
      out.write("	border: 3px solid #478bfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"checkbox\"]:checked:after {\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	content: \"\\f058\";\r\n");
      out.write("	color: #478bfb;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"checkbox\"]:checked+label .fas {\r\n");
      out.write("	animation: grow 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes grow { 50%{\r\n");
      out.write("	font-size: 80px;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>유형 선택</h2>\r\n");
      out.write("<h3>반려견의 증상 유형을 선택해주세요<p>최대 3개까지 가능합니다.</h3>\r\n");
      out.write("<section>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name = \"bodypart\" id=\"stool\">\r\n");
      out.write(" 		<label for=\"stool\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/stool.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"urine\">\r\n");
      out.write(" 		<label for=\"urine\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/urine.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"meal\">\r\n");
      out.write(" 		<label for=\"meal\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/meal.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"vomit\">\r\n");
      out.write(" 		<label for=\"vomit\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/vomit.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"ear\">\r\n");
      out.write(" 		<label for=\"ear\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/ear.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"face_dog\">\r\n");
      out.write(" 		<label for=\"face_dog\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/face_dog.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"eye\">\r\n");
      out.write(" 		<label for=\"eye\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/eye.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"paw\">\r\n");
      out.write(" 		<label for=\"paw\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/paw.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"joint\">\r\n");
      out.write(" 		<label for=\"joint\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/joint.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"skin\">\r\n");
      out.write(" 		<label for=\"skin\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/skin.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"tooth\">\r\n");
      out.write(" 		<label for=\"tooth\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/tooth.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"breath\">\r\n");
      out.write(" 		<label for=\"breath\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/breath.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"genitals_dog\">\r\n");
      out.write(" 		<label for=\"genitals_dog\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/genitals_dog.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"behavior_dog\">\r\n");
      out.write(" 		<label for=\"behavior_dog\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/behavior_dog.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"abdomen_dog\">\r\n");
      out.write(" 		<label for=\"abdomen_dog\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/abdomen_dog.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	<div class=\"tile\">\r\n");
      out.write(" 		<input type=\"checkbox\" name=\"bodypart\" id=\"waist_dog\">\r\n");
      out.write(" 		<label for=\"waist_dog\">\r\n");
      out.write(" 			<img src=\"resources/images/ogudoctor/self_category/waist_dog.png\" >\r\n");
      out.write(" 		</label>\r\n");
      out.write(" 	</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
