/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-31 06:58:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/rhj/oguogu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/oguogu/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690189635752L));
    _jspx_dependants.put("jar:file:/D:/rhj/oguogu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/oguogu/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>FAQ</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#title {\n");
      out.write("    width: 600px;\n");
      out.write("    height: 100px;\n");
      out.write("    background-color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    margin : auto;\n");
      out.write("    margin-top:60px;\n");
      out.write("    color: #FFA629;\n");
      out.write("    font-family: 'Bagel Fat One', cursive;        \n");
      out.write("    text-shadow: 1px 1px 2px #D1D1D1;\n");
      out.write("    font-size: 60pt;\n");
      out.write("    border: none;\n");
      out.write("    padding-top: 10px;\n");
      out.write("    justify-content: center; /* 가로 가운데 정렬 */\n");
      out.write("    align-items: center; /* 세로 가운데 정렬 */\n");
      out.write("    display: flex; /* Flexbox 사용 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#faqWrapper{\n");
      out.write("        width: 1130px;\n");
      out.write("        height: 1200px;\n");
      out.write("        margin: auto;\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\n");
      out.write("    }\n");
      out.write("#faqWrapper > ul > li:first-child {\n");
      out.write("        text-align: center;\n");
      out.write("        font-size:14pt;\n");
      out.write("        height:40px;\n");
      out.write("        vertical-align:middle;\n");
      out.write("        line-height:30px;\n");
      out.write("}\n");
      out.write("#divPaging {\n");
      out.write("          clear:both; \n");
      out.write("        margin:0 auto; \n");
      out.write("        width:220px; \n");
      out.write("        height:50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    #divPaging > div {\n");
      out.write("        float:left;\n");
      out.write("        width: 30px;\n");
      out.write("        margin:0 auto;\n");
      out.write("        text-align:center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("    #liSearchOption {clear:both;}\n");
      out.write("    #liSearchOption > div {\n");
      out.write("        margin:0 auto; \n");
      out.write("        margin-top: 30px; \n");
      out.write("        width:auto; \n");
      out.write("        height:100px;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".center {\n");
      out.write("        text-align : center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sidebar {\n");
      out.write("	width: 15%;\n");
      out.write("	background-color: white;\n");
      out.write("	font-size: 15pt;\n");
      out.write("	float: left;\n");
      out.write("	text-align: left;\n");
      out.write("	padding: 20px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	margin-top: 160px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write(".sidebar-menu li {\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("  list-style-type: none; \n");
      out.write("  text-align: left;\n");
      out.write("}\n");
      out.write(".sidebar-menu a {\n");
      out.write("  text-decoration: none;\n");
      out.write("  color: #333;\n");
      out.write("}\n");
      out.write(".table{\n");
      out.write("	width:1500px;\n");
      out.write("	margin:0 auto;\n");
      out.write("	float: right;\n");
      out.write("	margin-top: 100px;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("footer{\n");
      out.write("		width:1920px;\n");
      out.write("		display:flex;\n");
      out.write("		margin:auto;\n");
      out.write("		margin-top:20px;\n");
      out.write("		margin-bottom: 20px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\"\n");
      out.write("            src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.3.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("	function write_go() {\n");
      out.write("		//글쓰기로 이동하는 함수\n");
      out.write("		location.href = \"/faq_insertForm.do\";\n");
      out.write("}\n");
      out.write("    </script>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 헤더 구역 -->\n");
      out.write("	<header>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../home/home_top.jsp", out, false);
      out.write("\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("<div id=\"faqWrapper\" style=\"width: 1920px;\">\n");
      out.write("	<!-- 사이드바 구역 -->\n");
      out.write("	<div class=\"sidebar\">\n");
      out.write("    <ul class=\"sidebar-menu\">\n");
      out.write("      <li class=\"notice\"><a href=\"/sup_list.do\">공지사항</a></li>\n");
      out.write("      <hr>\n");
      out.write("      <li class=\"faq\" style=\"font-weight: bold;\"><a href=\"/faq_list.do\">문의사항</a></li>\n");
      out.write("      <hr>\n");
      out.write("      <li class=\"report\"><a href=\"/rep_list.do\">신고</a></li>\n");
      out.write("     </ul>\n");
      out.write("  </div>\n");
      out.write("  <!-- 게시판 리스트 구역 -->\n");
      out.write("  <div>\n");
      out.write("	<p id=\"title\">문의사항</p>\n");
      out.write("	</div>\n");
      out.write("  <div class=\"faq_list\">\n");
      out.write("	<table class=\"table\">\n");
      out.write("  <thead>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"col\">No.</th>\n");
      out.write("      <th scope=\"col\">제목</th>\n");
      out.write("      <th scope=\"col\">유형</th>\n");
      out.write("      <th scope=\"col\">작성자</th>\n");
      out.write("      <th scope=\"col\">작성 날짜</th>\n");
      out.write("      <th scope=\"col\">진행상황</th>\n");
      out.write("    </tr>\n");
      out.write("  </thead>\n");
      out.write("  <tbody>\n");
      out.write("  ");
      out.write("\n");
      out.write("   <tr>\n");
      out.write("      <th scope=\"row\">1</th>\n");
      out.write("      <td>반려동물 프로필 사진 어떻게 바꾸나요?</td>\n");
      out.write("      <td>강아지</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">2</th>\n");
      out.write("      <td>Jacob</td>\n");
      out.write("      <td>Thornton</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">3</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">4</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">5</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">6</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">7</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">8</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">9</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("      <th scope=\"row\">10</th>\n");
      out.write("      <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("      <td>hohoho</td>\n");
      out.write("      <td>2023/08/24</td>\n");
      out.write("      <td>답변 대기중</td>\n");
      out.write("    </tr>\n");
      out.write("   \n");
      out.write("   \n");
      out.write("  </tbody>\n");
      out.write("</table>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("		<center>\n");
      out.write("            <li id='liSearchOption'>\n");
      out.write("            	<form action=\"qnasearch.do?page=1\" method=\"post\">\n");
      out.write("            	<input type=\"button\" value=\"글쓰기\" style=\"float: right;\" onclick=\"write_go()\">\n");
      out.write("                <div>\n");
      out.write("                    <select name=\"searchtype\" >\n");
      out.write("                        <option value=\"qname\">제목</option>\n");
      out.write("                        <option value=\"qcontent\">내용</option>\n");
      out.write("                        <option value=\"qid\">작성자</option>                        \n");
      out.write("                    </select>\n");
      out.write("                    <input type=\"search\" name=\"keyword\">\n");
      out.write("                    <input type=\"submit\" value=\"검색\">\n");
      out.write("                </div>\n");
      out.write("                </form>\n");
      out.write("             </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("   </div>\n");
      out.write("   <br>\n");
      out.write("</center>\n");
      out.write("<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/home/home_bottom.jsp", out, false);
      out.write("\n");
      out.write("	</footer>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\" ></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
